# logging.file=E:\\zcyp-log\\zcyp_user.log
# logging.level.com.cloud.zcyp=debug
# logging.level.org.springframework.boot.autoconfigure: error

sms.host = http://gyytz.market.alicloudapi.com
sms.path = /sms/smsSend
sms.method = POST
sms.appcode = 31e364298648476da5cac4aa78719bc0

# mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

# �����ĸ��ļ������ã�dev��development��������������prod��product��������[��Ʒ]������
# spring.profiles.active=dev