# logging.file=E:\\zcyp-log\\zcyp_user.log
# logging.level.com.cloud.zcyp=debug
# logging.level.org.springframework.boot.autoconfigure: error

sms.host = http://gyytz.market.alicloudapi.com
sms.path = /sms/smsSend
sms.method = POST
sms.appcode = 31e364298648476da5cac4aa78719bc0

# mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

# 设置哪个文件起作用（dev【development】：开发环境；prod【product】：生产[产品]环境）
# spring.profiles.active=dev